version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  gcp-cli: circleci/gcp-cli@2.4.1
  gcp-gcr: circleci/gcp-gcr@0.15.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: redis
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      TZ: "Asia/Tokyo"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      # - run:
      #     name: Test
      #     command: |
      #       ./gradlew check jacocoTestReport
      # - codecov/upload
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  deploy:
    docker:
      - image: cimg/python:3.8.15
    environment:
      TERM: dumb
      TZ: "Asia/Tokyo"
      REPOSITORY_NAME: main
      IMAGE_NAME: app
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - when:
          condition:
            equal: [ spring-batch, << pipeline.git.branch >> ]
          steps:
            - gcp-gcr/gcr-auth:
                registry-url: asia-northeast1-docker.pkg.dev
            - gcp-gcr/build-image:
                image: $REPOSITORY_NAME/$IMAGE_NAME
                registry-url: asia-northeast1-docker.pkg.dev
            - gcp-gcr/push-image:
                image: $REPOSITORY_NAME/$IMAGE_NAME
                registry-url: asia-northeast1-docker.pkg.dev
             # - gcp-cli/install
             # - gcp-cli/initialize

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy
