version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      YARN_SILENT: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Build
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Deployment
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./.circleci/setup-heroku.sh
              ./.circleci/setup-retry.sh

              retry heroku plugins:install java
            #   heroku deploy:jar --jar app/build/libs/app.jar --app pinemz-emotions
            fi

