version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  gcp-gcr: circleci/gcp-gcr@0.15.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
      - image: redis
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      TZ: "Asia/Tokyo"
      YARN_SILENT: 1
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      # - run:
      #     name: Test
      #     command: |
      #       ./gradlew check jacocoTestReport
      # - codecov/upload
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: docker/app
          registry-url: asia-northeast1-docker.pkg.dev
      - gcp-gcr/push-image:
          image: docker/app
          registry-url: asia-northeast1-docker.pkg.dev
