spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always

logging:
  level:
    io.lettuce.core: INFO
    io.netty: WARN
    org.apache.http: WARN
    org.eclipse.jetty: WARN
    org.springframework: INFO
    org.hibernate.validator: WARN
    reactor: WARN
    twitter4j: INFO
