# General
# ---------------------------

spring:
  redis:
    database: 0
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

scheduling:
  enabled: true


# Cloud services
# ---------------------------

cloudstorage:
  credentials: ENC(UHFS3n8UOu4y5nJne+wgfqak4KLD2dKs2OK/FFgo4YKW3iWB9rmtcoiqKPAgDB0aEM3wzVs+vf/gMU9qCe4eQoV5q3/V8Cm0UXNBQsMuuTMMhyva9xvBggOj2lirIgjjFDH8f5dBrFV1P4qGHl7OxeDWE8j+PruYkMn5Yaalsqf53KnEvg+X7bOsK2fiEZGDUNpBCio1+aZwUhLq23vW32VOYSCfuDvuX64vLGUZ+L3Zvde04n4FQ8UIsqQS9jXzueJ8A7UlBdJi5LyQpG+eiD+4jJgTtyAxkPzxIjTHY/XkIaF3bJMUWlTwabiEPai+l8WqGz4GJP8j3CYYqvd5J0ATalH+dIl4tYSaZxan/irIRhmtOGwZxXqt+KMPsdoLqH0S7ISEf8zk45SVbAZItnwdwByZ9hCyxektcDu+nxSU4VJ5YecCLRt11P/Et5l4GPg4/fOq3ZD6rpCsh1RjWPwz0O7eHwbs6IIYADlPxVzQe8+eJ05Ou19In29YtiXQEG3TJ72Z1Vfuq/urGc4ia22qrD7+qgwHgAqj+8ny2f0XuN7nyi/8sy6T/0Xd63Ekt5mV9+3x9Tk0Aj1kzwZXUytJ2feH5wtuH2TLU9PCDnikOxf3tw2OS2zJyC14XQs5FrY6RqRA2Tl/BBdfgviP8AM6Vp2H1VvyheDLlp2nagDf3Vsyzhv+ZTAyjDXRoyZsDHaxwugmFbaWHIb5SuE0z1mZelSpqPZXyNyDIsaNSOCe+Sj8i4zhimYqnRHYXg05F4XSx3ctaC6F/iQFLD6LRMIxdTU6/V15ciHz6DuZF81Q/he9f5d+8URQc7QhA8CEfdMxR1TU7X4seIctcrMZorBS9tXU3NaQoafaaCzLMjGLEXqNiqzVr4fynk3fGc45WqzS3ZWOc5+xH9LKI5Gb62HPNVyeri7XFjm/eBCDqn0GOABPMKcTHLigrXLWtAz1wsCIrTtJ28tI0JDuEaJ4LgnAI3i75L6ozEz9KImIMuqO5+iEKaEXkDMeNd9ddWK9DpTYZjC8G4JuHWBL804/l2Rg+HL/8LqpaIILfBQgdu1lI8ti+xjL++LU95zy9M04XtSvCMzTSYZ4CtWDBMhAGfhdj1SEhYeca+mtVBu86XWJX0QtHbUA8B/nxXAPAqgtBzU8ISncpJERV/KuzNTaEWSn2mfYQK+5iQ0xyjwGSLu5A76M8EkZ2SGirie7eCLmCqjXjhYNVDy1El/+72sM0bzqXm2F+91pV2V5no/Fs/r5jgEL2yvb31+Jhe8Q7t6sIh6g2FMUrf0bVgGOpvL+2XE/mZw2H1UtrlPf2/zuMHDCz3suwzMBCSlDFhrRUi0zCKUWcFQBOWaNS7Jiamhnpb891BWyMXSTGNqoXziCgj52gKf8U3U6UGDd7tso3Bit60XgFdCQzJrjUcc4kfAvVt72xD6J4EJ1g0oJDJ4u6dhwGx+FSYx3xd/IILbiu1VQZueP/SXwBG0OMxY7HrNsCZ5mGpgFyOdaYB4ZxtwN4xjdB7fTGXIuK3FdGolMFFx11B7hkGZNdx2kAoKP6mgVHdCJaOcYOkPYNdMu+R/zF3yNH8WqqB8S8g2fZEnxSlmVlQscE/q6iMsz5BTLG2Fn8ITx2bR7YbDCh72SLeHrM7JU0KFbMp+OqRfBmtJZCaJ0bO8JsCzVJmPEl3obtlvrDu4rxMLPyNL3Dc/N4AIkWnYqMUWUUvYQX+AyYLhyeSkXnu7ZFRu7/Voppxg0fDDNuxZB0cYfR4zXJFDhDk+5Gf2M0LVx9hzdiX3pUJKqLI4hdgLbJ/HjhadzRtQGjR1FvXFgYpmjab+3GWxZV9DfcUa+K+/h8MqtWMbKbDXueMf+uhw/7B2kuLe8t1GG0GRvad+ZeRHOUr8hChPWoUUQQkPPnxSY3lsM0DDcfAkj7aM4ezu8Du3RpESE0YawcdUaglXm4B5DLKSOPPwol9jTc6MEchlNtcLKYWYDyKm2uOZiaUPb9YtaRsKTvCrOJIcsyXM8IxkaHmDlu3TEq/UTComS9VHjFSWDIW/SM5fUNthdBsxE6ytcgpnVAa8WcARRsXYokJdI+7yNDux9WTfU4SusVvC636vJ47Ws5NLeSkYDMv6C8NKeTeIxgQTsv9f5gaeHD0gyhqQdZ6MdBAPMtTRNC9O0+BNlXrQ3vcijMJK4REeWaee+tsX/Zx9S62OJ1rW97ZhWTnfbhOrgxvhpAe7azVNrj9ZnyNz3bek3MaM6uUgC5DH3ev///BOWzvmBfm662k++b8BY9igYzKVVtTKV10mlKMDoK5t12NbhJfuhXTntGEidX3rIkrMDOBhfYtQwDx+PYb8lG3hRF7nOPvRN13MperTJdUIZe2RuBodkz4a1epFl7MLqipJU1SXx7FaKdnC7gt42K7se9YRpAr3y8dBdSP2yeY3G/QBZBVqZrBlKF+rpcP+1fn+UKZqUiDsd27MZei74OCGIvj+QCobU/dLr/1xBubTnNZ1Jr7v6FR3+pSRPSnPaEPce+rN59M+tCwMenGRTCRRIq4kJBEwwwZ5HGT1msKWFvjmBmPdAa6sPCq7i1jyiUHBfWHIo7DIPsjdtp2xqKvhPxcCJsQPw8EXqRSY/n9eyosti9P/xweHMSnTlw/b6EaVvjS4F67zpRShrzbEQ+FtpRtpoFawJnB0PtxtdYRWW9RLSpl8EAs8dz3w16EAuhWCQF7E0hSfBhSDkNvcZTnMQyGQkA+lqOfVF1/8TgtkBG+FRro7+tdsBnhHMi4z8uctHEepMsyeVbMRdXOOCT8zPiaAfW4pJz3sM3YgIstX1vgq/2SDM1BjNOoyu/4YSqr7PMMOwbqJUJ68hE/wrz2tpc/eOGqMJjn+BIMpSsxvaZJbSxoizIhMA8aLEw79wy3qq9BSD90nr8+XLKu7fFPdoGNk8MeOIKAc0F9eOu1GC15hGSY8COuC4KtrKL5WHEIuI7fLRvGQ2tOnBKGNb+e6fq3twu3dxfpU7yBjNSIXg3uao4EdchmLu7byBVr5d7mc++C1UEpGOnFnzXpqOtZG633aO/fslmmzCv5l4oK0VJ4T8TjbqJHOH2fCG1f0HliRo6vbHq5KO8aIB9NtbskDX3VO9Aylz6I+QqA+kBcvMjsNrYn/x)
  images:
    - bucket: emotions-images
      name: ai1.png
    - bucket: emotions-images
      name: ai2.png
    - bucket: emotions-images
      name: ai3.png
    - bucket: emotions-images
      name: ai4.png

mackerel:
  api-key: ENC(Aykv+L+zf5hbP3GFPJHYI8U79xLxVRc8uWL9ZRuwB1WlQQglv9MQ/8z7dXeQKPkvxc91Y7IGjaIYxT1wsdcLXpWly7xC1YNZDbDLactMn0c=)
  graphs:
    elapsed-time:
      name: 'elapsed_time'


# Supported services
# ---------------------------

bookmeter:
  email: pinemz@gmail.com
  password: ENC(fg57iRP5oMPXcGUFlAQocfRLqN3pXmf11SBsCHW7JmGNWTCS8DhXwn48RB9ejLKy6dWCYKupbNtJQTdzrCz3Og==)

gravatar:
  email: pinemz@gmail.com
  password: ENC(Ce2Ae1eu9RcW3mQdWhaGPiUD3OJS0cXfmfUf7PqSYwgZ9RW1c1rknIkAnvB5ipPYRf2Y/6al6GoefpZWYMNnRQ==)
  addresses:
    - pinemz@gmail.com
    - pinemz@outlook.jp
    - pine@cpan.org
  images:
    - 7e4c74ed99b559d2dba24292a270677d
    - 91d702b2382ab7c03201724276ec8174
    - dceb9ad0d4645b348721f086dbe839fe
    - 8decd9236d7efd42d6527c35636d5551

twitter:
  consumer-key: ENC(20h70z4oVtiOJZOLikNiTdx6EONE6hzhU+7/rtc3RLCpb82LKFY+cH73CsvWflqQcQtcT4ID2EB8quChpXqq6g==)
  consumer-secret: ENC(BEWN0aIFc9alcybUnwh4zZeOMsjD4d3Ul4O0fr6LcyjVd4xm6omUsRpioGX4aZok5VgxNHHlncSM9d46/bihot/LAmllnIxxx7yTeouva9uohb/p6gZ2zXD2Jx7s4I0f)
  access-token: ENC(kXEkVtVzkxSu1zVG+cFrlbCpk5Ny5il6DzZsVzgeXo5j8OKj67+9bkg+x1KaD6Bpjx4Tsah1w9CC0VzH4zZ8zQokmdEBGzxbNM6YbQZTU/rtfb989ErZ4cuoCxXw/G39)
  access-token-secret: ENC(BDJWx5zFLuKb7bHlAfQnbhiZ8ex6uEKqTa3hVJGJMpz9JlPN2vIz2DUZxNnAr0JMMLNWtikcO2jzsta7UJo7lkcnNQJwHOM5BdPlzMvkAok=)
  connection-timeout: 30s
  read-timeout: 120s
